// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: ipfs/pb/ipfs.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IpfsReqSummary struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FileSize            int64    `protobuf:"varint,1,opt,name=fileSize,proto3" json:"fileSize,omitempty"`
	BlockCount          int64    `protobuf:"varint,2,opt,name=blockCount,proto3" json:"blockCount,omitempty"`
	StorageProviderList []string `protobuf:"bytes,3,rep,name=StorageProviderList,proto3" json:"StorageProviderList,omitempty"`
}

func (x *IpfsReqSummary) Reset() {
	*x = IpfsReqSummary{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ipfs_pb_ipfs_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IpfsReqSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IpfsReqSummary) ProtoMessage() {}

func (x *IpfsReqSummary) ProtoReflect() protoreflect.Message {
	mi := &file_ipfs_pb_ipfs_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IpfsReqSummary.ProtoReflect.Descriptor instead.
func (*IpfsReqSummary) Descriptor() ([]byte, []int) {
	return file_ipfs_pb_ipfs_proto_rawDescGZIP(), []int{0}
}

func (x *IpfsReqSummary) GetFileSize() int64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *IpfsReqSummary) GetBlockCount() int64 {
	if x != nil {
		return x.BlockCount
	}
	return 0
}

func (x *IpfsReqSummary) GetStorageProviderList() []string {
	if x != nil {
		return x.StorageProviderList
	}
	return nil
}

type IpfsReqBlock struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Index     int64  `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Content   []byte `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	BlockSize int64  `protobuf:"varint,3,opt,name=blockSize,proto3" json:"blockSize,omitempty"`
	CheckSum  int64  `protobuf:"varint,4,opt,name=checkSum,proto3" json:"checkSum,omitempty"`
}

func (x *IpfsReqBlock) Reset() {
	*x = IpfsReqBlock{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ipfs_pb_ipfs_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IpfsReqBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IpfsReqBlock) ProtoMessage() {}

func (x *IpfsReqBlock) ProtoReflect() protoreflect.Message {
	mi := &file_ipfs_pb_ipfs_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IpfsReqBlock.ProtoReflect.Descriptor instead.
func (*IpfsReqBlock) Descriptor() ([]byte, []int) {
	return file_ipfs_pb_ipfs_proto_rawDescGZIP(), []int{1}
}

func (x *IpfsReqBlock) GetIndex() int64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *IpfsReqBlock) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *IpfsReqBlock) GetBlockSize() int64 {
	if x != nil {
		return x.BlockSize
	}
	return 0
}

func (x *IpfsReqBlock) GetCheckSum() int64 {
	if x != nil {
		return x.CheckSum
	}
	return 0
}

type IpfsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CID string `protobuf:"bytes,2,opt,name=CID,proto3" json:"CID,omitempty"`
	// Types that are assignable to Options:
	//
	//	*IpfsReq_Summary
	//	*IpfsReq_Block
	Options isIpfsReq_Options `protobuf_oneof:"options"`
}

func (x *IpfsReq) Reset() {
	*x = IpfsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ipfs_pb_ipfs_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IpfsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IpfsReq) ProtoMessage() {}

func (x *IpfsReq) ProtoReflect() protoreflect.Message {
	mi := &file_ipfs_pb_ipfs_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IpfsReq.ProtoReflect.Descriptor instead.
func (*IpfsReq) Descriptor() ([]byte, []int) {
	return file_ipfs_pb_ipfs_proto_rawDescGZIP(), []int{2}
}

func (x *IpfsReq) GetCID() string {
	if x != nil {
		return x.CID
	}
	return ""
}

func (m *IpfsReq) GetOptions() isIpfsReq_Options {
	if m != nil {
		return m.Options
	}
	return nil
}

func (x *IpfsReq) GetSummary() *IpfsReqSummary {
	if x, ok := x.GetOptions().(*IpfsReq_Summary); ok {
		return x.Summary
	}
	return nil
}

func (x *IpfsReq) GetBlock() *IpfsReqBlock {
	if x, ok := x.GetOptions().(*IpfsReq_Block); ok {
		return x.Block
	}
	return nil
}

type isIpfsReq_Options interface {
	isIpfsReq_Options()
}

type IpfsReq_Summary struct {
	Summary *IpfsReqSummary `protobuf:"bytes,3,opt,name=summary,proto3,oneof"`
}

type IpfsReq_Block struct {
	Block *IpfsReqBlock `protobuf:"bytes,4,opt,name=block,proto3,oneof"`
}

func (*IpfsReq_Summary) isIpfsReq_Options() {}

func (*IpfsReq_Block) isIpfsReq_Options() {}

type IpfsRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code   int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Result string `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *IpfsRes) Reset() {
	*x = IpfsRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ipfs_pb_ipfs_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IpfsRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IpfsRes) ProtoMessage() {}

func (x *IpfsRes) ProtoReflect() protoreflect.Message {
	mi := &file_ipfs_pb_ipfs_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IpfsRes.ProtoReflect.Descriptor instead.
func (*IpfsRes) Descriptor() ([]byte, []int) {
	return file_ipfs_pb_ipfs_proto_rawDescGZIP(), []int{3}
}

func (x *IpfsRes) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *IpfsRes) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

var File_ipfs_pb_ipfs_proto protoreflect.FileDescriptor

var file_ipfs_pb_ipfs_proto_rawDesc = []byte{
	0x0a, 0x12, 0x69, 0x70, 0x66, 0x73, 0x2f, 0x70, 0x62, 0x2f, 0x69, 0x70, 0x66, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x7e, 0x0a, 0x0e, 0x49, 0x70, 0x66, 0x73,
	0x52, 0x65, 0x71, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x69,
	0x6c, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x66, 0x69,
	0x6c, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x43,
	0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x62, 0x6c, 0x6f, 0x63,
	0x6b, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x30, 0x0a, 0x13, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67,
	0x65, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x03, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x13, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x50, 0x72, 0x6f, 0x76,
	0x69, 0x64, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x78, 0x0a, 0x0c, 0x49, 0x70, 0x66, 0x73,
	0x52, 0x65, 0x71, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65,
	0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x18,
	0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x62, 0x6c, 0x6f, 0x63,
	0x6b, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x62, 0x6c, 0x6f,
	0x63, 0x6b, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x53,
	0x75, 0x6d, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x53,
	0x75, 0x6d, 0x22, 0x80, 0x01, 0x0a, 0x07, 0x49, 0x70, 0x66, 0x73, 0x52, 0x65, 0x71, 0x12, 0x10,
	0x0a, 0x03, 0x43, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x43, 0x49, 0x44,
	0x12, 0x2e, 0x0a, 0x07, 0x73, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x12, 0x2e, 0x70, 0x62, 0x2e, 0x49, 0x70, 0x66, 0x73, 0x52, 0x65, 0x71, 0x53, 0x75,
	0x6d, 0x6d, 0x61, 0x72, 0x79, 0x48, 0x00, 0x52, 0x07, 0x73, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79,
	0x12, 0x28, 0x0a, 0x05, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x10, 0x2e, 0x70, 0x62, 0x2e, 0x49, 0x70, 0x66, 0x73, 0x52, 0x65, 0x71, 0x42, 0x6c, 0x6f, 0x63,
	0x6b, 0x48, 0x00, 0x52, 0x05, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x42, 0x09, 0x0a, 0x07, 0x6f, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x35, 0x0a, 0x07, 0x49, 0x70, 0x66, 0x73, 0x52, 0x65, 0x73,
	0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04,
	0x63, 0x6f, 0x64, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x42, 0x09, 0x5a, 0x07,
	0x69, 0x70, 0x66, 0x73, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ipfs_pb_ipfs_proto_rawDescOnce sync.Once
	file_ipfs_pb_ipfs_proto_rawDescData = file_ipfs_pb_ipfs_proto_rawDesc
)

func file_ipfs_pb_ipfs_proto_rawDescGZIP() []byte {
	file_ipfs_pb_ipfs_proto_rawDescOnce.Do(func() {
		file_ipfs_pb_ipfs_proto_rawDescData = protoimpl.X.CompressGZIP(file_ipfs_pb_ipfs_proto_rawDescData)
	})
	return file_ipfs_pb_ipfs_proto_rawDescData
}

var file_ipfs_pb_ipfs_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_ipfs_pb_ipfs_proto_goTypes = []interface{}{
	(*IpfsReqSummary)(nil), // 0: pb.IpfsReqSummary
	(*IpfsReqBlock)(nil),   // 1: pb.IpfsReqBlock
	(*IpfsReq)(nil),        // 2: pb.IpfsReq
	(*IpfsRes)(nil),        // 3: pb.IpfsRes
}
var file_ipfs_pb_ipfs_proto_depIdxs = []int32{
	0, // 0: pb.IpfsReq.summary:type_name -> pb.IpfsReqSummary
	1, // 1: pb.IpfsReq.block:type_name -> pb.IpfsReqBlock
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_ipfs_pb_ipfs_proto_init() }
func file_ipfs_pb_ipfs_proto_init() {
	if File_ipfs_pb_ipfs_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ipfs_pb_ipfs_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IpfsReqSummary); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ipfs_pb_ipfs_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IpfsReqBlock); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ipfs_pb_ipfs_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IpfsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ipfs_pb_ipfs_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IpfsRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_ipfs_pb_ipfs_proto_msgTypes[2].OneofWrappers = []interface{}{
		(*IpfsReq_Summary)(nil),
		(*IpfsReq_Block)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ipfs_pb_ipfs_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ipfs_pb_ipfs_proto_goTypes,
		DependencyIndexes: file_ipfs_pb_ipfs_proto_depIdxs,
		MessageInfos:      file_ipfs_pb_ipfs_proto_msgTypes,
	}.Build()
	File_ipfs_pb_ipfs_proto = out.File
	file_ipfs_pb_ipfs_proto_rawDesc = nil
	file_ipfs_pb_ipfs_proto_goTypes = nil
	file_ipfs_pb_ipfs_proto_depIdxs = nil
}
