// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: dmsg.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProtocolID int32

const (
	ProtocolID_CREATE_MAILBOX_RES         ProtocolID = 0
	ProtocolID_CREATE_MAILBOX_REQ         ProtocolID = 1
	ProtocolID_RELEASE_MAILBOX_RES        ProtocolID = 2
	ProtocolID_RELEASE_MAILBOX_REQ        ProtocolID = 3
	ProtocolID_SEEK_MAILBOX_RES           ProtocolID = 4
	ProtocolID_SEEK_MAILBOX_REQ           ProtocolID = 5
	ProtocolID_READ_MAILBOX_MSG_RES       ProtocolID = 6
	ProtocolID_READ_MAILBOX_MSG_REQ       ProtocolID = 7
	ProtocolID_SEND_MSG_RES               ProtocolID = 8
	ProtocolID_SEND_MSG_REQ               ProtocolID = 9
	ProtocolID_CUSTOM_STREAM_PROTOCOL_RES ProtocolID = 10
	ProtocolID_CUSTOM_STREAM_PROTOCOL_REQ ProtocolID = 11
	ProtocolID_CUSTOM_PUBSUB_PROTOCOL_RES ProtocolID = 12
	ProtocolID_CUSTOM_PUBSUB_PROTOCOL_REQ ProtocolID = 13
)

// Enum value maps for ProtocolID.
var (
	ProtocolID_name = map[int32]string{
		0:  "CREATE_MAILBOX_RES",
		1:  "CREATE_MAILBOX_REQ",
		2:  "RELEASE_MAILBOX_RES",
		3:  "RELEASE_MAILBOX_REQ",
		4:  "SEEK_MAILBOX_RES",
		5:  "SEEK_MAILBOX_REQ",
		6:  "READ_MAILBOX_MSG_RES",
		7:  "READ_MAILBOX_MSG_REQ",
		8:  "SEND_MSG_RES",
		9:  "SEND_MSG_REQ",
		10: "CUSTOM_STREAM_PROTOCOL_RES",
		11: "CUSTOM_STREAM_PROTOCOL_REQ",
		12: "CUSTOM_PUBSUB_PROTOCOL_RES",
		13: "CUSTOM_PUBSUB_PROTOCOL_REQ",
	}
	ProtocolID_value = map[string]int32{
		"CREATE_MAILBOX_RES":         0,
		"CREATE_MAILBOX_REQ":         1,
		"RELEASE_MAILBOX_RES":        2,
		"RELEASE_MAILBOX_REQ":        3,
		"SEEK_MAILBOX_RES":           4,
		"SEEK_MAILBOX_REQ":           5,
		"READ_MAILBOX_MSG_RES":       6,
		"READ_MAILBOX_MSG_REQ":       7,
		"SEND_MSG_RES":               8,
		"SEND_MSG_REQ":               9,
		"CUSTOM_STREAM_PROTOCOL_RES": 10,
		"CUSTOM_STREAM_PROTOCOL_REQ": 11,
		"CUSTOM_PUBSUB_PROTOCOL_RES": 12,
		"CUSTOM_PUBSUB_PROTOCOL_REQ": 13,
	}
)

func (x ProtocolID) Enum() *ProtocolID {
	p := new(ProtocolID)
	*p = x
	return p
}

func (x ProtocolID) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProtocolID) Descriptor() protoreflect.EnumDescriptor {
	return file_dmsg_proto_enumTypes[0].Descriptor()
}

func (ProtocolID) Type() protoreflect.EnumType {
	return &file_dmsg_proto_enumTypes[0]
}

func (x ProtocolID) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProtocolID.Descriptor instead.
func (ProtocolID) EnumDescriptor() ([]byte, []int) {
	return file_dmsg_proto_rawDescGZIP(), []int{0}
}

type BasicData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         string     `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ProtocolID ProtocolID `protobuf:"varint,2,opt,name=protocolID,proto3,enum=pb.ProtocolID" json:"protocolID,omitempty"`
	Timestamp  int64      `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	PeerId     string     `protobuf:"bytes,4,opt,name=peerId,proto3" json:"peerId,omitempty"`
	SignPubKey []byte     `protobuf:"bytes,5,opt,name=signPubKey,proto3" json:"signPubKey,omitempty"`
	DestPubkey string     `protobuf:"bytes,6,opt,name=destPubkey,proto3" json:"destPubkey,omitempty"`
	Sign       []byte     `protobuf:"bytes,7,opt,name=sign,proto3" json:"sign,omitempty"`
	Ver        string     `protobuf:"bytes,8,opt,name=ver,proto3" json:"ver,omitempty"`
}

func (x *BasicData) Reset() {
	*x = BasicData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dmsg_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BasicData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BasicData) ProtoMessage() {}

func (x *BasicData) ProtoReflect() protoreflect.Message {
	mi := &file_dmsg_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BasicData.ProtoReflect.Descriptor instead.
func (*BasicData) Descriptor() ([]byte, []int) {
	return file_dmsg_proto_rawDescGZIP(), []int{0}
}

func (x *BasicData) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BasicData) GetProtocolID() ProtocolID {
	if x != nil {
		return x.ProtocolID
	}
	return ProtocolID_CREATE_MAILBOX_RES
}

func (x *BasicData) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *BasicData) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

func (x *BasicData) GetSignPubKey() []byte {
	if x != nil {
		return x.SignPubKey
	}
	return nil
}

func (x *BasicData) GetDestPubkey() string {
	if x != nil {
		return x.DestPubkey
	}
	return ""
}

func (x *BasicData) GetSign() []byte {
	if x != nil {
		return x.Sign
	}
	return nil
}

func (x *BasicData) GetVer() string {
	if x != nil {
		return x.Ver
	}
	return ""
}

type RetCode struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code   int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Result string `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *RetCode) Reset() {
	*x = RetCode{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dmsg_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RetCode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetCode) ProtoMessage() {}

func (x *RetCode) ProtoReflect() protoreflect.Message {
	mi := &file_dmsg_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetCode.ProtoReflect.Descriptor instead.
func (*RetCode) Descriptor() ([]byte, []int) {
	return file_dmsg_proto_rawDescGZIP(), []int{1}
}

func (x *RetCode) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *RetCode) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type SendMsgReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BasicData  *BasicData `protobuf:"bytes,1,opt,name=basicData,proto3" json:"basicData,omitempty"`
	SrcPubkey  string     `protobuf:"bytes,2,opt,name=srcPubkey,proto3" json:"srcPubkey,omitempty"`
	MsgContent []byte     `protobuf:"bytes,3,opt,name=msgContent,proto3" json:"msgContent,omitempty"`
}

func (x *SendMsgReq) Reset() {
	*x = SendMsgReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dmsg_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendMsgReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMsgReq) ProtoMessage() {}

func (x *SendMsgReq) ProtoReflect() protoreflect.Message {
	mi := &file_dmsg_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMsgReq.ProtoReflect.Descriptor instead.
func (*SendMsgReq) Descriptor() ([]byte, []int) {
	return file_dmsg_proto_rawDescGZIP(), []int{2}
}

func (x *SendMsgReq) GetBasicData() *BasicData {
	if x != nil {
		return x.BasicData
	}
	return nil
}

func (x *SendMsgReq) GetSrcPubkey() string {
	if x != nil {
		return x.SrcPubkey
	}
	return ""
}

func (x *SendMsgReq) GetMsgContent() []byte {
	if x != nil {
		return x.MsgContent
	}
	return nil
}

type ReadMailboxMsgReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BasicData *BasicData `protobuf:"bytes,1,opt,name=basicData,proto3" json:"basicData,omitempty"`
}

func (x *ReadMailboxMsgReq) Reset() {
	*x = ReadMailboxMsgReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dmsg_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadMailboxMsgReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadMailboxMsgReq) ProtoMessage() {}

func (x *ReadMailboxMsgReq) ProtoReflect() protoreflect.Message {
	mi := &file_dmsg_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadMailboxMsgReq.ProtoReflect.Descriptor instead.
func (*ReadMailboxMsgReq) Descriptor() ([]byte, []int) {
	return file_dmsg_proto_rawDescGZIP(), []int{3}
}

func (x *ReadMailboxMsgReq) GetBasicData() *BasicData {
	if x != nil {
		return x.BasicData
	}
	return nil
}

type MailboxMsgData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key        string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	MsgContent []byte `protobuf:"bytes,2,opt,name=msgContent,proto3" json:"msgContent,omitempty"`
}

func (x *MailboxMsgData) Reset() {
	*x = MailboxMsgData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dmsg_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MailboxMsgData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MailboxMsgData) ProtoMessage() {}

func (x *MailboxMsgData) ProtoReflect() protoreflect.Message {
	mi := &file_dmsg_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MailboxMsgData.ProtoReflect.Descriptor instead.
func (*MailboxMsgData) Descriptor() ([]byte, []int) {
	return file_dmsg_proto_rawDescGZIP(), []int{4}
}

func (x *MailboxMsgData) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *MailboxMsgData) GetMsgContent() []byte {
	if x != nil {
		return x.MsgContent
	}
	return nil
}

type ReadMailboxMsgRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BasicData       *BasicData        `protobuf:"bytes,1,opt,name=basicData,proto3" json:"basicData,omitempty"`
	MailboxMsgDatas []*MailboxMsgData `protobuf:"bytes,2,rep,name=mailboxMsgDatas,proto3" json:"mailboxMsgDatas,omitempty"`
	RetCode         *RetCode          `protobuf:"bytes,3,opt,name=retCode,proto3" json:"retCode,omitempty"`
}

func (x *ReadMailboxMsgRes) Reset() {
	*x = ReadMailboxMsgRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dmsg_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadMailboxMsgRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadMailboxMsgRes) ProtoMessage() {}

func (x *ReadMailboxMsgRes) ProtoReflect() protoreflect.Message {
	mi := &file_dmsg_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadMailboxMsgRes.ProtoReflect.Descriptor instead.
func (*ReadMailboxMsgRes) Descriptor() ([]byte, []int) {
	return file_dmsg_proto_rawDescGZIP(), []int{5}
}

func (x *ReadMailboxMsgRes) GetBasicData() *BasicData {
	if x != nil {
		return x.BasicData
	}
	return nil
}

func (x *ReadMailboxMsgRes) GetMailboxMsgDatas() []*MailboxMsgData {
	if x != nil {
		return x.MailboxMsgDatas
	}
	return nil
}

func (x *ReadMailboxMsgRes) GetRetCode() *RetCode {
	if x != nil {
		return x.RetCode
	}
	return nil
}

type CreateMailboxReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BasicData *BasicData `protobuf:"bytes,1,opt,name=basicData,proto3" json:"basicData,omitempty"`
}

func (x *CreateMailboxReq) Reset() {
	*x = CreateMailboxReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dmsg_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateMailboxReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMailboxReq) ProtoMessage() {}

func (x *CreateMailboxReq) ProtoReflect() protoreflect.Message {
	mi := &file_dmsg_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMailboxReq.ProtoReflect.Descriptor instead.
func (*CreateMailboxReq) Descriptor() ([]byte, []int) {
	return file_dmsg_proto_rawDescGZIP(), []int{6}
}

func (x *CreateMailboxReq) GetBasicData() *BasicData {
	if x != nil {
		return x.BasicData
	}
	return nil
}

type CreateMailboxRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BasicData *BasicData `protobuf:"bytes,1,opt,name=basicData,proto3" json:"basicData,omitempty"`
	RetCode   *RetCode   `protobuf:"bytes,2,opt,name=retCode,proto3" json:"retCode,omitempty"`
}

func (x *CreateMailboxRes) Reset() {
	*x = CreateMailboxRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dmsg_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateMailboxRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMailboxRes) ProtoMessage() {}

func (x *CreateMailboxRes) ProtoReflect() protoreflect.Message {
	mi := &file_dmsg_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMailboxRes.ProtoReflect.Descriptor instead.
func (*CreateMailboxRes) Descriptor() ([]byte, []int) {
	return file_dmsg_proto_rawDescGZIP(), []int{7}
}

func (x *CreateMailboxRes) GetBasicData() *BasicData {
	if x != nil {
		return x.BasicData
	}
	return nil
}

func (x *CreateMailboxRes) GetRetCode() *RetCode {
	if x != nil {
		return x.RetCode
	}
	return nil
}

type ReleaseMailboxReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BasicData *BasicData `protobuf:"bytes,1,opt,name=basicData,proto3" json:"basicData,omitempty"`
}

func (x *ReleaseMailboxReq) Reset() {
	*x = ReleaseMailboxReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dmsg_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReleaseMailboxReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseMailboxReq) ProtoMessage() {}

func (x *ReleaseMailboxReq) ProtoReflect() protoreflect.Message {
	mi := &file_dmsg_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseMailboxReq.ProtoReflect.Descriptor instead.
func (*ReleaseMailboxReq) Descriptor() ([]byte, []int) {
	return file_dmsg_proto_rawDescGZIP(), []int{8}
}

func (x *ReleaseMailboxReq) GetBasicData() *BasicData {
	if x != nil {
		return x.BasicData
	}
	return nil
}

type ReleaseMailboxRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BasicData *BasicData `protobuf:"bytes,1,opt,name=basicData,proto3" json:"basicData,omitempty"`
	RetCode   *RetCode   `protobuf:"bytes,2,opt,name=retCode,proto3" json:"retCode,omitempty"`
}

func (x *ReleaseMailboxRes) Reset() {
	*x = ReleaseMailboxRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dmsg_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReleaseMailboxRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseMailboxRes) ProtoMessage() {}

func (x *ReleaseMailboxRes) ProtoReflect() protoreflect.Message {
	mi := &file_dmsg_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseMailboxRes.ProtoReflect.Descriptor instead.
func (*ReleaseMailboxRes) Descriptor() ([]byte, []int) {
	return file_dmsg_proto_rawDescGZIP(), []int{9}
}

func (x *ReleaseMailboxRes) GetBasicData() *BasicData {
	if x != nil {
		return x.BasicData
	}
	return nil
}

func (x *ReleaseMailboxRes) GetRetCode() *RetCode {
	if x != nil {
		return x.RetCode
	}
	return nil
}

type SeekMailboxReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BasicData *BasicData `protobuf:"bytes,1,opt,name=basicData,proto3" json:"basicData,omitempty"`
}

func (x *SeekMailboxReq) Reset() {
	*x = SeekMailboxReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dmsg_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SeekMailboxReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeekMailboxReq) ProtoMessage() {}

func (x *SeekMailboxReq) ProtoReflect() protoreflect.Message {
	mi := &file_dmsg_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeekMailboxReq.ProtoReflect.Descriptor instead.
func (*SeekMailboxReq) Descriptor() ([]byte, []int) {
	return file_dmsg_proto_rawDescGZIP(), []int{10}
}

func (x *SeekMailboxReq) GetBasicData() *BasicData {
	if x != nil {
		return x.BasicData
	}
	return nil
}

type SeekMailboxRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BasicData *BasicData `protobuf:"bytes,1,opt,name=basicData,proto3" json:"basicData,omitempty"`
	PeerId    string     `protobuf:"bytes,2,opt,name=peerId,proto3" json:"peerId,omitempty"`
	RetCode   *RetCode   `protobuf:"bytes,3,opt,name=retCode,proto3" json:"retCode,omitempty"`
}

func (x *SeekMailboxRes) Reset() {
	*x = SeekMailboxRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dmsg_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SeekMailboxRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeekMailboxRes) ProtoMessage() {}

func (x *SeekMailboxRes) ProtoReflect() protoreflect.Message {
	mi := &file_dmsg_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeekMailboxRes.ProtoReflect.Descriptor instead.
func (*SeekMailboxRes) Descriptor() ([]byte, []int) {
	return file_dmsg_proto_rawDescGZIP(), []int{11}
}

func (x *SeekMailboxRes) GetBasicData() *BasicData {
	if x != nil {
		return x.BasicData
	}
	return nil
}

func (x *SeekMailboxRes) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

func (x *SeekMailboxRes) GetRetCode() *RetCode {
	if x != nil {
		return x.RetCode
	}
	return nil
}

type CustomProtocolReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BasicData        *BasicData `protobuf:"bytes,1,opt,name=basicData,proto3" json:"basicData,omitempty"`
	CustomProtocolID string     `protobuf:"bytes,2,opt,name=customProtocolID,proto3" json:"customProtocolID,omitempty"`
	Content          []byte     `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
}

func (x *CustomProtocolReq) Reset() {
	*x = CustomProtocolReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dmsg_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CustomProtocolReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomProtocolReq) ProtoMessage() {}

func (x *CustomProtocolReq) ProtoReflect() protoreflect.Message {
	mi := &file_dmsg_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomProtocolReq.ProtoReflect.Descriptor instead.
func (*CustomProtocolReq) Descriptor() ([]byte, []int) {
	return file_dmsg_proto_rawDescGZIP(), []int{12}
}

func (x *CustomProtocolReq) GetBasicData() *BasicData {
	if x != nil {
		return x.BasicData
	}
	return nil
}

func (x *CustomProtocolReq) GetCustomProtocolID() string {
	if x != nil {
		return x.CustomProtocolID
	}
	return ""
}

func (x *CustomProtocolReq) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

type CustomProtocolRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BasicData        *BasicData `protobuf:"bytes,1,opt,name=basicData,proto3" json:"basicData,omitempty"`
	CustomProtocolID string     `protobuf:"bytes,2,opt,name=customProtocolID,proto3" json:"customProtocolID,omitempty"`
	Content          []byte     `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	RetCode          *RetCode   `protobuf:"bytes,4,opt,name=retCode,proto3" json:"retCode,omitempty"`
}

func (x *CustomProtocolRes) Reset() {
	*x = CustomProtocolRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dmsg_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CustomProtocolRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomProtocolRes) ProtoMessage() {}

func (x *CustomProtocolRes) ProtoReflect() protoreflect.Message {
	mi := &file_dmsg_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomProtocolRes.ProtoReflect.Descriptor instead.
func (*CustomProtocolRes) Descriptor() ([]byte, []int) {
	return file_dmsg_proto_rawDescGZIP(), []int{13}
}

func (x *CustomProtocolRes) GetBasicData() *BasicData {
	if x != nil {
		return x.BasicData
	}
	return nil
}

func (x *CustomProtocolRes) GetCustomProtocolID() string {
	if x != nil {
		return x.CustomProtocolID
	}
	return ""
}

func (x *CustomProtocolRes) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *CustomProtocolRes) GetRetCode() *RetCode {
	if x != nil {
		return x.RetCode
	}
	return nil
}

var File_dmsg_proto protoreflect.FileDescriptor

var file_dmsg_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x64, 0x6d, 0x73, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62,
	0x22, 0xe7, 0x01, 0x0a, 0x09, 0x42, 0x61, 0x73, 0x69, 0x63, 0x44, 0x61, 0x74, 0x61, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x2e,
	0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x0e, 0x2e, 0x70, 0x62, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c,
	0x49, 0x44, 0x52, 0x0a, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x49, 0x44, 0x12, 0x1c,
	0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x16, 0x0a, 0x06,
	0x70, 0x65, 0x65, 0x72, 0x49, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x65,
	0x65, 0x72, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x69, 0x67, 0x6e, 0x50, 0x75, 0x62, 0x4b,
	0x65, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a, 0x73, 0x69, 0x67, 0x6e, 0x50, 0x75,
	0x62, 0x4b, 0x65, 0x79, 0x12, 0x1e, 0x0a, 0x0a, 0x64, 0x65, 0x73, 0x74, 0x50, 0x75, 0x62, 0x6b,
	0x65, 0x79, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x64, 0x65, 0x73, 0x74, 0x50, 0x75,
	0x62, 0x6b, 0x65, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x67, 0x6e, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x04, 0x73, 0x69, 0x67, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x76, 0x65, 0x72, 0x18,
	0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x76, 0x65, 0x72, 0x22, 0x35, 0x0a, 0x07, 0x52, 0x65,
	0x74, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x22, 0x77, 0x0a, 0x0a, 0x53, 0x65, 0x6e, 0x64, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x71, 0x12,
	0x2b, 0x0a, 0x09, 0x62, 0x61, 0x73, 0x69, 0x63, 0x44, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x62, 0x2e, 0x42, 0x61, 0x73, 0x69, 0x63, 0x44, 0x61, 0x74,
	0x61, 0x52, 0x09, 0x62, 0x61, 0x73, 0x69, 0x63, 0x44, 0x61, 0x74, 0x61, 0x12, 0x1c, 0x0a, 0x09,
	0x73, 0x72, 0x63, 0x50, 0x75, 0x62, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x73, 0x72, 0x63, 0x50, 0x75, 0x62, 0x6b, 0x65, 0x79, 0x12, 0x1e, 0x0a, 0x0a, 0x6d, 0x73,
	0x67, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a,
	0x6d, 0x73, 0x67, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x22, 0x40, 0x0a, 0x11, 0x52, 0x65,
	0x61, 0x64, 0x4d, 0x61, 0x69, 0x6c, 0x62, 0x6f, 0x78, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x71, 0x12,
	0x2b, 0x0a, 0x09, 0x62, 0x61, 0x73, 0x69, 0x63, 0x44, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x62, 0x2e, 0x42, 0x61, 0x73, 0x69, 0x63, 0x44, 0x61, 0x74,
	0x61, 0x52, 0x09, 0x62, 0x61, 0x73, 0x69, 0x63, 0x44, 0x61, 0x74, 0x61, 0x22, 0x42, 0x0a, 0x0e,
	0x4d, 0x61, 0x69, 0x6c, 0x62, 0x6f, 0x78, 0x4d, 0x73, 0x67, 0x44, 0x61, 0x74, 0x61, 0x12, 0x10,
	0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79,
	0x12, 0x1e, 0x0a, 0x0a, 0x6d, 0x73, 0x67, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a, 0x6d, 0x73, 0x67, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74,
	0x22, 0xa5, 0x01, 0x0a, 0x11, 0x52, 0x65, 0x61, 0x64, 0x4d, 0x61, 0x69, 0x6c, 0x62, 0x6f, 0x78,
	0x4d, 0x73, 0x67, 0x52, 0x65, 0x73, 0x12, 0x2b, 0x0a, 0x09, 0x62, 0x61, 0x73, 0x69, 0x63, 0x44,
	0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x62, 0x2e, 0x42,
	0x61, 0x73, 0x69, 0x63, 0x44, 0x61, 0x74, 0x61, 0x52, 0x09, 0x62, 0x61, 0x73, 0x69, 0x63, 0x44,
	0x61, 0x74, 0x61, 0x12, 0x3c, 0x0a, 0x0f, 0x6d, 0x61, 0x69, 0x6c, 0x62, 0x6f, 0x78, 0x4d, 0x73,
	0x67, 0x44, 0x61, 0x74, 0x61, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70,
	0x62, 0x2e, 0x4d, 0x61, 0x69, 0x6c, 0x62, 0x6f, 0x78, 0x4d, 0x73, 0x67, 0x44, 0x61, 0x74, 0x61,
	0x52, 0x0f, 0x6d, 0x61, 0x69, 0x6c, 0x62, 0x6f, 0x78, 0x4d, 0x73, 0x67, 0x44, 0x61, 0x74, 0x61,
	0x73, 0x12, 0x25, 0x0a, 0x07, 0x72, 0x65, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x52,
	0x07, 0x72, 0x65, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x22, 0x3f, 0x0a, 0x10, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x4d, 0x61, 0x69, 0x6c, 0x62, 0x6f, 0x78, 0x52, 0x65, 0x71, 0x12, 0x2b, 0x0a, 0x09,
	0x62, 0x61, 0x73, 0x69, 0x63, 0x44, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0d, 0x2e, 0x70, 0x62, 0x2e, 0x42, 0x61, 0x73, 0x69, 0x63, 0x44, 0x61, 0x74, 0x61, 0x52, 0x09,
	0x62, 0x61, 0x73, 0x69, 0x63, 0x44, 0x61, 0x74, 0x61, 0x22, 0x66, 0x0a, 0x10, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x4d, 0x61, 0x69, 0x6c, 0x62, 0x6f, 0x78, 0x52, 0x65, 0x73, 0x12, 0x2b, 0x0a,
	0x09, 0x62, 0x61, 0x73, 0x69, 0x63, 0x44, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0d, 0x2e, 0x70, 0x62, 0x2e, 0x42, 0x61, 0x73, 0x69, 0x63, 0x44, 0x61, 0x74, 0x61, 0x52,
	0x09, 0x62, 0x61, 0x73, 0x69, 0x63, 0x44, 0x61, 0x74, 0x61, 0x12, 0x25, 0x0a, 0x07, 0x72, 0x65,
	0x74, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x70, 0x62,
	0x2e, 0x52, 0x65, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x07, 0x72, 0x65, 0x74, 0x43, 0x6f, 0x64,
	0x65, 0x22, 0x40, 0x0a, 0x11, 0x52, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x4d, 0x61, 0x69, 0x6c,
	0x62, 0x6f, 0x78, 0x52, 0x65, 0x71, 0x12, 0x2b, 0x0a, 0x09, 0x62, 0x61, 0x73, 0x69, 0x63, 0x44,
	0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x62, 0x2e, 0x42,
	0x61, 0x73, 0x69, 0x63, 0x44, 0x61, 0x74, 0x61, 0x52, 0x09, 0x62, 0x61, 0x73, 0x69, 0x63, 0x44,
	0x61, 0x74, 0x61, 0x22, 0x67, 0x0a, 0x11, 0x52, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x4d, 0x61,
	0x69, 0x6c, 0x62, 0x6f, 0x78, 0x52, 0x65, 0x73, 0x12, 0x2b, 0x0a, 0x09, 0x62, 0x61, 0x73, 0x69,
	0x63, 0x44, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x62,
	0x2e, 0x42, 0x61, 0x73, 0x69, 0x63, 0x44, 0x61, 0x74, 0x61, 0x52, 0x09, 0x62, 0x61, 0x73, 0x69,
	0x63, 0x44, 0x61, 0x74, 0x61, 0x12, 0x25, 0x0a, 0x07, 0x72, 0x65, 0x74, 0x43, 0x6f, 0x64, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x74, 0x43,
	0x6f, 0x64, 0x65, 0x52, 0x07, 0x72, 0x65, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x22, 0x3d, 0x0a, 0x0e,
	0x53, 0x65, 0x65, 0x6b, 0x4d, 0x61, 0x69, 0x6c, 0x62, 0x6f, 0x78, 0x52, 0x65, 0x71, 0x12, 0x2b,
	0x0a, 0x09, 0x62, 0x61, 0x73, 0x69, 0x63, 0x44, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x62, 0x2e, 0x42, 0x61, 0x73, 0x69, 0x63, 0x44, 0x61, 0x74, 0x61,
	0x52, 0x09, 0x62, 0x61, 0x73, 0x69, 0x63, 0x44, 0x61, 0x74, 0x61, 0x22, 0x7c, 0x0a, 0x0e, 0x53,
	0x65, 0x65, 0x6b, 0x4d, 0x61, 0x69, 0x6c, 0x62, 0x6f, 0x78, 0x52, 0x65, 0x73, 0x12, 0x2b, 0x0a,
	0x09, 0x62, 0x61, 0x73, 0x69, 0x63, 0x44, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0d, 0x2e, 0x70, 0x62, 0x2e, 0x42, 0x61, 0x73, 0x69, 0x63, 0x44, 0x61, 0x74, 0x61, 0x52,
	0x09, 0x62, 0x61, 0x73, 0x69, 0x63, 0x44, 0x61, 0x74, 0x61, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x65,
	0x65, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x65, 0x65, 0x72,
	0x49, 0x64, 0x12, 0x25, 0x0a, 0x07, 0x72, 0x65, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x74, 0x43, 0x6f, 0x64, 0x65,
	0x52, 0x07, 0x72, 0x65, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x22, 0x86, 0x01, 0x0a, 0x11, 0x43, 0x75,
	0x73, 0x74, 0x6f, 0x6d, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x52, 0x65, 0x71, 0x12,
	0x2b, 0x0a, 0x09, 0x62, 0x61, 0x73, 0x69, 0x63, 0x44, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x62, 0x2e, 0x42, 0x61, 0x73, 0x69, 0x63, 0x44, 0x61, 0x74,
	0x61, 0x52, 0x09, 0x62, 0x61, 0x73, 0x69, 0x63, 0x44, 0x61, 0x74, 0x61, 0x12, 0x2a, 0x0a, 0x10,
	0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x49, 0x44,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x50, 0x72,
	0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x49, 0x44, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74,
	0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65,
	0x6e, 0x74, 0x22, 0xad, 0x01, 0x0a, 0x11, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x50, 0x72, 0x6f,
	0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x52, 0x65, 0x73, 0x12, 0x2b, 0x0a, 0x09, 0x62, 0x61, 0x73, 0x69,
	0x63, 0x44, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x62,
	0x2e, 0x42, 0x61, 0x73, 0x69, 0x63, 0x44, 0x61, 0x74, 0x61, 0x52, 0x09, 0x62, 0x61, 0x73, 0x69,
	0x63, 0x44, 0x61, 0x74, 0x61, 0x12, 0x2a, 0x0a, 0x10, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x50,
	0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x10, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x49,
	0x44, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x25, 0x0a, 0x07, 0x72,
	0x65, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x70,
	0x62, 0x2e, 0x52, 0x65, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x07, 0x72, 0x65, 0x74, 0x43, 0x6f,
	0x64, 0x65, 0x2a, 0xf2, 0x02, 0x0a, 0x0a, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x49,
	0x44, 0x12, 0x16, 0x0a, 0x12, 0x43, 0x52, 0x45, 0x41, 0x54, 0x45, 0x5f, 0x4d, 0x41, 0x49, 0x4c,
	0x42, 0x4f, 0x58, 0x5f, 0x52, 0x45, 0x53, 0x10, 0x00, 0x12, 0x16, 0x0a, 0x12, 0x43, 0x52, 0x45,
	0x41, 0x54, 0x45, 0x5f, 0x4d, 0x41, 0x49, 0x4c, 0x42, 0x4f, 0x58, 0x5f, 0x52, 0x45, 0x51, 0x10,
	0x01, 0x12, 0x17, 0x0a, 0x13, 0x52, 0x45, 0x4c, 0x45, 0x41, 0x53, 0x45, 0x5f, 0x4d, 0x41, 0x49,
	0x4c, 0x42, 0x4f, 0x58, 0x5f, 0x52, 0x45, 0x53, 0x10, 0x02, 0x12, 0x17, 0x0a, 0x13, 0x52, 0x45,
	0x4c, 0x45, 0x41, 0x53, 0x45, 0x5f, 0x4d, 0x41, 0x49, 0x4c, 0x42, 0x4f, 0x58, 0x5f, 0x52, 0x45,
	0x51, 0x10, 0x03, 0x12, 0x14, 0x0a, 0x10, 0x53, 0x45, 0x45, 0x4b, 0x5f, 0x4d, 0x41, 0x49, 0x4c,
	0x42, 0x4f, 0x58, 0x5f, 0x52, 0x45, 0x53, 0x10, 0x04, 0x12, 0x14, 0x0a, 0x10, 0x53, 0x45, 0x45,
	0x4b, 0x5f, 0x4d, 0x41, 0x49, 0x4c, 0x42, 0x4f, 0x58, 0x5f, 0x52, 0x45, 0x51, 0x10, 0x05, 0x12,
	0x18, 0x0a, 0x14, 0x52, 0x45, 0x41, 0x44, 0x5f, 0x4d, 0x41, 0x49, 0x4c, 0x42, 0x4f, 0x58, 0x5f,
	0x4d, 0x53, 0x47, 0x5f, 0x52, 0x45, 0x53, 0x10, 0x06, 0x12, 0x18, 0x0a, 0x14, 0x52, 0x45, 0x41,
	0x44, 0x5f, 0x4d, 0x41, 0x49, 0x4c, 0x42, 0x4f, 0x58, 0x5f, 0x4d, 0x53, 0x47, 0x5f, 0x52, 0x45,
	0x51, 0x10, 0x07, 0x12, 0x10, 0x0a, 0x0c, 0x53, 0x45, 0x4e, 0x44, 0x5f, 0x4d, 0x53, 0x47, 0x5f,
	0x52, 0x45, 0x53, 0x10, 0x08, 0x12, 0x10, 0x0a, 0x0c, 0x53, 0x45, 0x4e, 0x44, 0x5f, 0x4d, 0x53,
	0x47, 0x5f, 0x52, 0x45, 0x51, 0x10, 0x09, 0x12, 0x1e, 0x0a, 0x1a, 0x43, 0x55, 0x53, 0x54, 0x4f,
	0x4d, 0x5f, 0x53, 0x54, 0x52, 0x45, 0x41, 0x4d, 0x5f, 0x50, 0x52, 0x4f, 0x54, 0x4f, 0x43, 0x4f,
	0x4c, 0x5f, 0x52, 0x45, 0x53, 0x10, 0x0a, 0x12, 0x1e, 0x0a, 0x1a, 0x43, 0x55, 0x53, 0x54, 0x4f,
	0x4d, 0x5f, 0x53, 0x54, 0x52, 0x45, 0x41, 0x4d, 0x5f, 0x50, 0x52, 0x4f, 0x54, 0x4f, 0x43, 0x4f,
	0x4c, 0x5f, 0x52, 0x45, 0x51, 0x10, 0x0b, 0x12, 0x1e, 0x0a, 0x1a, 0x43, 0x55, 0x53, 0x54, 0x4f,
	0x4d, 0x5f, 0x50, 0x55, 0x42, 0x53, 0x55, 0x42, 0x5f, 0x50, 0x52, 0x4f, 0x54, 0x4f, 0x43, 0x4f,
	0x4c, 0x5f, 0x52, 0x45, 0x53, 0x10, 0x0c, 0x12, 0x1e, 0x0a, 0x1a, 0x43, 0x55, 0x53, 0x54, 0x4f,
	0x4d, 0x5f, 0x50, 0x55, 0x42, 0x53, 0x55, 0x42, 0x5f, 0x50, 0x52, 0x4f, 0x54, 0x4f, 0x43, 0x4f,
	0x4c, 0x5f, 0x52, 0x45, 0x51, 0x10, 0x0d, 0x42, 0x09, 0x5a, 0x07, 0x64, 0x6d, 0x73, 0x67, 0x2f,
	0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_dmsg_proto_rawDescOnce sync.Once
	file_dmsg_proto_rawDescData = file_dmsg_proto_rawDesc
)

func file_dmsg_proto_rawDescGZIP() []byte {
	file_dmsg_proto_rawDescOnce.Do(func() {
		file_dmsg_proto_rawDescData = protoimpl.X.CompressGZIP(file_dmsg_proto_rawDescData)
	})
	return file_dmsg_proto_rawDescData
}

var file_dmsg_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_dmsg_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_dmsg_proto_goTypes = []interface{}{
	(ProtocolID)(0),           // 0: pb.ProtocolID
	(*BasicData)(nil),         // 1: pb.BasicData
	(*RetCode)(nil),           // 2: pb.RetCode
	(*SendMsgReq)(nil),        // 3: pb.SendMsgReq
	(*ReadMailboxMsgReq)(nil), // 4: pb.ReadMailboxMsgReq
	(*MailboxMsgData)(nil),    // 5: pb.MailboxMsgData
	(*ReadMailboxMsgRes)(nil), // 6: pb.ReadMailboxMsgRes
	(*CreateMailboxReq)(nil),  // 7: pb.CreateMailboxReq
	(*CreateMailboxRes)(nil),  // 8: pb.CreateMailboxRes
	(*ReleaseMailboxReq)(nil), // 9: pb.ReleaseMailboxReq
	(*ReleaseMailboxRes)(nil), // 10: pb.ReleaseMailboxRes
	(*SeekMailboxReq)(nil),    // 11: pb.SeekMailboxReq
	(*SeekMailboxRes)(nil),    // 12: pb.SeekMailboxRes
	(*CustomProtocolReq)(nil), // 13: pb.CustomProtocolReq
	(*CustomProtocolRes)(nil), // 14: pb.CustomProtocolRes
}
var file_dmsg_proto_depIdxs = []int32{
	0,  // 0: pb.BasicData.protocolID:type_name -> pb.ProtocolID
	1,  // 1: pb.SendMsgReq.basicData:type_name -> pb.BasicData
	1,  // 2: pb.ReadMailboxMsgReq.basicData:type_name -> pb.BasicData
	1,  // 3: pb.ReadMailboxMsgRes.basicData:type_name -> pb.BasicData
	5,  // 4: pb.ReadMailboxMsgRes.mailboxMsgDatas:type_name -> pb.MailboxMsgData
	2,  // 5: pb.ReadMailboxMsgRes.retCode:type_name -> pb.RetCode
	1,  // 6: pb.CreateMailboxReq.basicData:type_name -> pb.BasicData
	1,  // 7: pb.CreateMailboxRes.basicData:type_name -> pb.BasicData
	2,  // 8: pb.CreateMailboxRes.retCode:type_name -> pb.RetCode
	1,  // 9: pb.ReleaseMailboxReq.basicData:type_name -> pb.BasicData
	1,  // 10: pb.ReleaseMailboxRes.basicData:type_name -> pb.BasicData
	2,  // 11: pb.ReleaseMailboxRes.retCode:type_name -> pb.RetCode
	1,  // 12: pb.SeekMailboxReq.basicData:type_name -> pb.BasicData
	1,  // 13: pb.SeekMailboxRes.basicData:type_name -> pb.BasicData
	2,  // 14: pb.SeekMailboxRes.retCode:type_name -> pb.RetCode
	1,  // 15: pb.CustomProtocolReq.basicData:type_name -> pb.BasicData
	1,  // 16: pb.CustomProtocolRes.basicData:type_name -> pb.BasicData
	2,  // 17: pb.CustomProtocolRes.retCode:type_name -> pb.RetCode
	18, // [18:18] is the sub-list for method output_type
	18, // [18:18] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_dmsg_proto_init() }
func file_dmsg_proto_init() {
	if File_dmsg_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_dmsg_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BasicData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dmsg_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RetCode); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dmsg_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendMsgReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dmsg_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadMailboxMsgReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dmsg_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MailboxMsgData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dmsg_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadMailboxMsgRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dmsg_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateMailboxReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dmsg_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateMailboxRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dmsg_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReleaseMailboxReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dmsg_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReleaseMailboxRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dmsg_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SeekMailboxReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dmsg_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SeekMailboxRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dmsg_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CustomProtocolReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dmsg_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CustomProtocolRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_dmsg_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_dmsg_proto_goTypes,
		DependencyIndexes: file_dmsg_proto_depIdxs,
		EnumInfos:         file_dmsg_proto_enumTypes,
		MessageInfos:      file_dmsg_proto_msgTypes,
	}.Build()
	File_dmsg_proto = out.File
	file_dmsg_proto_rawDesc = nil
	file_dmsg_proto_goTypes = nil
	file_dmsg_proto_depIdxs = nil
}
