// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: dmsg.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PID int32

const (
	PID_CREATE_MAILBOX_REQ    PID = 0
	PID_CREATE_MAILBOX_RES    PID = 1
	PID_RELEASE_MAILBOX_REQ   PID = 2
	PID_RELEASE_MAILBOX_RES   PID = 3
	PID_SEEK_MAILBOX_REQ      PID = 4
	PID_SEEK_MAILBOX_RES      PID = 5
	PID_READ_MAILBOX_REQ      PID = 6
	PID_READ_MAILBOX_RES      PID = 7
	PID_CREATE_MSG_PUBSUB_REQ PID = 8
	PID_CREATE_MSG_PUBSUB_RES PID = 9
	PID_MSG_REQ               PID = 10
	PID_MSG_RES               PID = 11
	PID_CREATE_CHANNEL_REQ    PID = 12
	PID_CREATE_CHANNEL_RES    PID = 13
	PID_QUERY_PEER_REQ        PID = 14
	PID_QUERY_PEER_RES        PID = 15
	PID_CUSTOM_STREAM_REQ     PID = 16
	PID_CUSTOM_STREAM_RES     PID = 17
)

// Enum value maps for PID.
var (
	PID_name = map[int32]string{
		0:  "CREATE_MAILBOX_REQ",
		1:  "CREATE_MAILBOX_RES",
		2:  "RELEASE_MAILBOX_REQ",
		3:  "RELEASE_MAILBOX_RES",
		4:  "SEEK_MAILBOX_REQ",
		5:  "SEEK_MAILBOX_RES",
		6:  "READ_MAILBOX_REQ",
		7:  "READ_MAILBOX_RES",
		8:  "CREATE_MSG_PUBSUB_REQ",
		9:  "CREATE_MSG_PUBSUB_RES",
		10: "MSG_REQ",
		11: "MSG_RES",
		12: "CREATE_CHANNEL_REQ",
		13: "CREATE_CHANNEL_RES",
		14: "QUERY_PEER_REQ",
		15: "QUERY_PEER_RES",
		16: "CUSTOM_STREAM_REQ",
		17: "CUSTOM_STREAM_RES",
	}
	PID_value = map[string]int32{
		"CREATE_MAILBOX_REQ":    0,
		"CREATE_MAILBOX_RES":    1,
		"RELEASE_MAILBOX_REQ":   2,
		"RELEASE_MAILBOX_RES":   3,
		"SEEK_MAILBOX_REQ":      4,
		"SEEK_MAILBOX_RES":      5,
		"READ_MAILBOX_REQ":      6,
		"READ_MAILBOX_RES":      7,
		"CREATE_MSG_PUBSUB_REQ": 8,
		"CREATE_MSG_PUBSUB_RES": 9,
		"MSG_REQ":               10,
		"MSG_RES":               11,
		"CREATE_CHANNEL_REQ":    12,
		"CREATE_CHANNEL_RES":    13,
		"QUERY_PEER_REQ":        14,
		"QUERY_PEER_RES":        15,
		"CUSTOM_STREAM_REQ":     16,
		"CUSTOM_STREAM_RES":     17,
	}
)

func (x PID) Enum() *PID {
	p := new(PID)
	*p = x
	return p
}

func (x PID) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PID) Descriptor() protoreflect.EnumDescriptor {
	return file_dmsg_proto_enumTypes[0].Descriptor()
}

func (PID) Type() protoreflect.EnumType {
	return &file_dmsg_proto_enumTypes[0]
}

func (x PID) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PID.Descriptor instead.
func (PID) EnumDescriptor() ([]byte, []int) {
	return file_dmsg_proto_rawDescGZIP(), []int{0}
}

type BasicData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID     string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	PID    PID    `protobuf:"varint,2,opt,name=PID,proto3,enum=pb.PID" json:"PID,omitempty"`
	TS     int64  `protobuf:"varint,3,opt,name=TS,proto3" json:"TS,omitempty"`
	PeerID string `protobuf:"bytes,4,opt,name=peerID,proto3" json:"peerID,omitempty"`
	Pubkey string `protobuf:"bytes,5,opt,name=pubkey,proto3" json:"pubkey,omitempty"`
	Sig    []byte `protobuf:"bytes,7,opt,name=sig,proto3" json:"sig,omitempty"`
	Ver    string `protobuf:"bytes,8,opt,name=ver,proto3" json:"ver,omitempty"`
}

func (x *BasicData) Reset() {
	*x = BasicData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dmsg_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BasicData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BasicData) ProtoMessage() {}

func (x *BasicData) ProtoReflect() protoreflect.Message {
	mi := &file_dmsg_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BasicData.ProtoReflect.Descriptor instead.
func (*BasicData) Descriptor() ([]byte, []int) {
	return file_dmsg_proto_rawDescGZIP(), []int{0}
}

func (x *BasicData) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *BasicData) GetPID() PID {
	if x != nil {
		return x.PID
	}
	return PID_CREATE_MAILBOX_REQ
}

func (x *BasicData) GetTS() int64 {
	if x != nil {
		return x.TS
	}
	return 0
}

func (x *BasicData) GetPeerID() string {
	if x != nil {
		return x.PeerID
	}
	return ""
}

func (x *BasicData) GetPubkey() string {
	if x != nil {
		return x.Pubkey
	}
	return ""
}

func (x *BasicData) GetSig() []byte {
	if x != nil {
		return x.Sig
	}
	return nil
}

func (x *BasicData) GetVer() string {
	if x != nil {
		return x.Ver
	}
	return ""
}

type RetCode struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code   int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Result string `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *RetCode) Reset() {
	*x = RetCode{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dmsg_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RetCode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetCode) ProtoMessage() {}

func (x *RetCode) ProtoReflect() protoreflect.Message {
	mi := &file_dmsg_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetCode.ProtoReflect.Descriptor instead.
func (*RetCode) Descriptor() ([]byte, []int) {
	return file_dmsg_proto_rawDescGZIP(), []int{1}
}

func (x *RetCode) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *RetCode) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type ReadMailboxReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BasicData *BasicData `protobuf:"bytes,1,opt,name=basicData,proto3" json:"basicData,omitempty"`
	ClearMode bool       `protobuf:"varint,2,opt,name=clearMode,proto3" json:"clearMode,omitempty"`
}

func (x *ReadMailboxReq) Reset() {
	*x = ReadMailboxReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dmsg_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadMailboxReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadMailboxReq) ProtoMessage() {}

func (x *ReadMailboxReq) ProtoReflect() protoreflect.Message {
	mi := &file_dmsg_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadMailboxReq.ProtoReflect.Descriptor instead.
func (*ReadMailboxReq) Descriptor() ([]byte, []int) {
	return file_dmsg_proto_rawDescGZIP(), []int{2}
}

func (x *ReadMailboxReq) GetBasicData() *BasicData {
	if x != nil {
		return x.BasicData
	}
	return nil
}

func (x *ReadMailboxReq) GetClearMode() bool {
	if x != nil {
		return x.ClearMode
	}
	return false
}

type MailboxItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key     string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Content []byte `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
}

func (x *MailboxItem) Reset() {
	*x = MailboxItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dmsg_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MailboxItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MailboxItem) ProtoMessage() {}

func (x *MailboxItem) ProtoReflect() protoreflect.Message {
	mi := &file_dmsg_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MailboxItem.ProtoReflect.Descriptor instead.
func (*MailboxItem) Descriptor() ([]byte, []int) {
	return file_dmsg_proto_rawDescGZIP(), []int{3}
}

func (x *MailboxItem) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *MailboxItem) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

type ReadMailboxRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BasicData   *BasicData     `protobuf:"bytes,1,opt,name=basicData,proto3" json:"basicData,omitempty"`
	ContentList []*MailboxItem `protobuf:"bytes,2,rep,name=contentList,proto3" json:"contentList,omitempty"`
	ExistData   bool           `protobuf:"varint,3,opt,name=existData,proto3" json:"existData,omitempty"`
	RetCode     *RetCode       `protobuf:"bytes,4,opt,name=retCode,proto3" json:"retCode,omitempty"`
}

func (x *ReadMailboxRes) Reset() {
	*x = ReadMailboxRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dmsg_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadMailboxRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadMailboxRes) ProtoMessage() {}

func (x *ReadMailboxRes) ProtoReflect() protoreflect.Message {
	mi := &file_dmsg_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadMailboxRes.ProtoReflect.Descriptor instead.
func (*ReadMailboxRes) Descriptor() ([]byte, []int) {
	return file_dmsg_proto_rawDescGZIP(), []int{4}
}

func (x *ReadMailboxRes) GetBasicData() *BasicData {
	if x != nil {
		return x.BasicData
	}
	return nil
}

func (x *ReadMailboxRes) GetContentList() []*MailboxItem {
	if x != nil {
		return x.ContentList
	}
	return nil
}

func (x *ReadMailboxRes) GetExistData() bool {
	if x != nil {
		return x.ExistData
	}
	return false
}

func (x *ReadMailboxRes) GetRetCode() *RetCode {
	if x != nil {
		return x.RetCode
	}
	return nil
}

type CreateMailboxReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BasicData *BasicData `protobuf:"bytes,1,opt,name=basicData,proto3" json:"basicData,omitempty"`
}

func (x *CreateMailboxReq) Reset() {
	*x = CreateMailboxReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dmsg_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateMailboxReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMailboxReq) ProtoMessage() {}

func (x *CreateMailboxReq) ProtoReflect() protoreflect.Message {
	mi := &file_dmsg_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMailboxReq.ProtoReflect.Descriptor instead.
func (*CreateMailboxReq) Descriptor() ([]byte, []int) {
	return file_dmsg_proto_rawDescGZIP(), []int{5}
}

func (x *CreateMailboxReq) GetBasicData() *BasicData {
	if x != nil {
		return x.BasicData
	}
	return nil
}

type CreateMailboxRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BasicData *BasicData `protobuf:"bytes,1,opt,name=basicData,proto3" json:"basicData,omitempty"`
	RetCode   *RetCode   `protobuf:"bytes,2,opt,name=retCode,proto3" json:"retCode,omitempty"`
}

func (x *CreateMailboxRes) Reset() {
	*x = CreateMailboxRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dmsg_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateMailboxRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMailboxRes) ProtoMessage() {}

func (x *CreateMailboxRes) ProtoReflect() protoreflect.Message {
	mi := &file_dmsg_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMailboxRes.ProtoReflect.Descriptor instead.
func (*CreateMailboxRes) Descriptor() ([]byte, []int) {
	return file_dmsg_proto_rawDescGZIP(), []int{6}
}

func (x *CreateMailboxRes) GetBasicData() *BasicData {
	if x != nil {
		return x.BasicData
	}
	return nil
}

func (x *CreateMailboxRes) GetRetCode() *RetCode {
	if x != nil {
		return x.RetCode
	}
	return nil
}

type ReleaseMailboxReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BasicData *BasicData `protobuf:"bytes,1,opt,name=basicData,proto3" json:"basicData,omitempty"`
}

func (x *ReleaseMailboxReq) Reset() {
	*x = ReleaseMailboxReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dmsg_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReleaseMailboxReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseMailboxReq) ProtoMessage() {}

func (x *ReleaseMailboxReq) ProtoReflect() protoreflect.Message {
	mi := &file_dmsg_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseMailboxReq.ProtoReflect.Descriptor instead.
func (*ReleaseMailboxReq) Descriptor() ([]byte, []int) {
	return file_dmsg_proto_rawDescGZIP(), []int{7}
}

func (x *ReleaseMailboxReq) GetBasicData() *BasicData {
	if x != nil {
		return x.BasicData
	}
	return nil
}

type ReleaseMailboxRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BasicData *BasicData `protobuf:"bytes,1,opt,name=basicData,proto3" json:"basicData,omitempty"`
	RetCode   *RetCode   `protobuf:"bytes,2,opt,name=retCode,proto3" json:"retCode,omitempty"`
}

func (x *ReleaseMailboxRes) Reset() {
	*x = ReleaseMailboxRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dmsg_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReleaseMailboxRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseMailboxRes) ProtoMessage() {}

func (x *ReleaseMailboxRes) ProtoReflect() protoreflect.Message {
	mi := &file_dmsg_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseMailboxRes.ProtoReflect.Descriptor instead.
func (*ReleaseMailboxRes) Descriptor() ([]byte, []int) {
	return file_dmsg_proto_rawDescGZIP(), []int{8}
}

func (x *ReleaseMailboxRes) GetBasicData() *BasicData {
	if x != nil {
		return x.BasicData
	}
	return nil
}

func (x *ReleaseMailboxRes) GetRetCode() *RetCode {
	if x != nil {
		return x.RetCode
	}
	return nil
}

type SeekMailboxReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BasicData *BasicData `protobuf:"bytes,1,opt,name=basicData,proto3" json:"basicData,omitempty"`
}

func (x *SeekMailboxReq) Reset() {
	*x = SeekMailboxReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dmsg_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SeekMailboxReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeekMailboxReq) ProtoMessage() {}

func (x *SeekMailboxReq) ProtoReflect() protoreflect.Message {
	mi := &file_dmsg_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeekMailboxReq.ProtoReflect.Descriptor instead.
func (*SeekMailboxReq) Descriptor() ([]byte, []int) {
	return file_dmsg_proto_rawDescGZIP(), []int{9}
}

func (x *SeekMailboxReq) GetBasicData() *BasicData {
	if x != nil {
		return x.BasicData
	}
	return nil
}

type SeekMailboxRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BasicData *BasicData `protobuf:"bytes,1,opt,name=basicData,proto3" json:"basicData,omitempty"`
	RetCode   *RetCode   `protobuf:"bytes,3,opt,name=retCode,proto3" json:"retCode,omitempty"`
}

func (x *SeekMailboxRes) Reset() {
	*x = SeekMailboxRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dmsg_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SeekMailboxRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeekMailboxRes) ProtoMessage() {}

func (x *SeekMailboxRes) ProtoReflect() protoreflect.Message {
	mi := &file_dmsg_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeekMailboxRes.ProtoReflect.Descriptor instead.
func (*SeekMailboxRes) Descriptor() ([]byte, []int) {
	return file_dmsg_proto_rawDescGZIP(), []int{10}
}

func (x *SeekMailboxRes) GetBasicData() *BasicData {
	if x != nil {
		return x.BasicData
	}
	return nil
}

func (x *SeekMailboxRes) GetRetCode() *RetCode {
	if x != nil {
		return x.RetCode
	}
	return nil
}

type CreatePubsubReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BasicData *BasicData `protobuf:"bytes,1,opt,name=basicData,proto3" json:"basicData,omitempty"`
	Key       string     `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *CreatePubsubReq) Reset() {
	*x = CreatePubsubReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dmsg_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreatePubsubReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePubsubReq) ProtoMessage() {}

func (x *CreatePubsubReq) ProtoReflect() protoreflect.Message {
	mi := &file_dmsg_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePubsubReq.ProtoReflect.Descriptor instead.
func (*CreatePubsubReq) Descriptor() ([]byte, []int) {
	return file_dmsg_proto_rawDescGZIP(), []int{11}
}

func (x *CreatePubsubReq) GetBasicData() *BasicData {
	if x != nil {
		return x.BasicData
	}
	return nil
}

func (x *CreatePubsubReq) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type CreatePubsubRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BasicData *BasicData `protobuf:"bytes,1,opt,name=basicData,proto3" json:"basicData,omitempty"`
	RetCode   *RetCode   `protobuf:"bytes,2,opt,name=retCode,proto3" json:"retCode,omitempty"`
}

func (x *CreatePubsubRes) Reset() {
	*x = CreatePubsubRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dmsg_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreatePubsubRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePubsubRes) ProtoMessage() {}

func (x *CreatePubsubRes) ProtoReflect() protoreflect.Message {
	mi := &file_dmsg_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePubsubRes.ProtoReflect.Descriptor instead.
func (*CreatePubsubRes) Descriptor() ([]byte, []int) {
	return file_dmsg_proto_rawDescGZIP(), []int{12}
}

func (x *CreatePubsubRes) GetBasicData() *BasicData {
	if x != nil {
		return x.BasicData
	}
	return nil
}

func (x *CreatePubsubRes) GetRetCode() *RetCode {
	if x != nil {
		return x.RetCode
	}
	return nil
}

type MsgReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BasicData  *BasicData `protobuf:"bytes,1,opt,name=basicData,proto3" json:"basicData,omitempty"`
	DestPubkey string     `protobuf:"bytes,2,opt,name=destPubkey,proto3" json:"destPubkey,omitempty"`
	Content    []byte     `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
}

func (x *MsgReq) Reset() {
	*x = MsgReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dmsg_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgReq) ProtoMessage() {}

func (x *MsgReq) ProtoReflect() protoreflect.Message {
	mi := &file_dmsg_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgReq.ProtoReflect.Descriptor instead.
func (*MsgReq) Descriptor() ([]byte, []int) {
	return file_dmsg_proto_rawDescGZIP(), []int{13}
}

func (x *MsgReq) GetBasicData() *BasicData {
	if x != nil {
		return x.BasicData
	}
	return nil
}

func (x *MsgReq) GetDestPubkey() string {
	if x != nil {
		return x.DestPubkey
	}
	return ""
}

func (x *MsgReq) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

type MsgRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BasicData *BasicData `protobuf:"bytes,1,opt,name=basicData,proto3" json:"basicData,omitempty"`
	RetCode   *RetCode   `protobuf:"bytes,2,opt,name=retCode,proto3" json:"retCode,omitempty"`
	Content   []byte     `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
}

func (x *MsgRes) Reset() {
	*x = MsgRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dmsg_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgRes) ProtoMessage() {}

func (x *MsgRes) ProtoReflect() protoreflect.Message {
	mi := &file_dmsg_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgRes.ProtoReflect.Descriptor instead.
func (*MsgRes) Descriptor() ([]byte, []int) {
	return file_dmsg_proto_rawDescGZIP(), []int{14}
}

func (x *MsgRes) GetBasicData() *BasicData {
	if x != nil {
		return x.BasicData
	}
	return nil
}

func (x *MsgRes) GetRetCode() *RetCode {
	if x != nil {
		return x.RetCode
	}
	return nil
}

func (x *MsgRes) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

type QueryPeerReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BasicData *BasicData `protobuf:"bytes,1,opt,name=basicData,proto3" json:"basicData,omitempty"`
	Pid       string     `protobuf:"bytes,2,opt,name=pid,proto3" json:"pid,omitempty"`
}

func (x *QueryPeerReq) Reset() {
	*x = QueryPeerReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dmsg_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryPeerReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryPeerReq) ProtoMessage() {}

func (x *QueryPeerReq) ProtoReflect() protoreflect.Message {
	mi := &file_dmsg_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryPeerReq.ProtoReflect.Descriptor instead.
func (*QueryPeerReq) Descriptor() ([]byte, []int) {
	return file_dmsg_proto_rawDescGZIP(), []int{15}
}

func (x *QueryPeerReq) GetBasicData() *BasicData {
	if x != nil {
		return x.BasicData
	}
	return nil
}

func (x *QueryPeerReq) GetPid() string {
	if x != nil {
		return x.Pid
	}
	return ""
}

type QueryPeerRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BasicData *BasicData `protobuf:"bytes,1,opt,name=basicData,proto3" json:"basicData,omitempty"`
	RetCode   *RetCode   `protobuf:"bytes,2,opt,name=retCode,proto3" json:"retCode,omitempty"`
}

func (x *QueryPeerRes) Reset() {
	*x = QueryPeerRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dmsg_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryPeerRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryPeerRes) ProtoMessage() {}

func (x *QueryPeerRes) ProtoReflect() protoreflect.Message {
	mi := &file_dmsg_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryPeerRes.ProtoReflect.Descriptor instead.
func (*QueryPeerRes) Descriptor() ([]byte, []int) {
	return file_dmsg_proto_rawDescGZIP(), []int{16}
}

func (x *QueryPeerRes) GetBasicData() *BasicData {
	if x != nil {
		return x.BasicData
	}
	return nil
}

func (x *QueryPeerRes) GetRetCode() *RetCode {
	if x != nil {
		return x.RetCode
	}
	return nil
}

type CustomProtocolReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BasicData *BasicData `protobuf:"bytes,1,opt,name=basicData,proto3" json:"basicData,omitempty"`
	PID       string     `protobuf:"bytes,2,opt,name=pID,proto3" json:"pID,omitempty"`
	Content   []byte     `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
}

func (x *CustomProtocolReq) Reset() {
	*x = CustomProtocolReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dmsg_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CustomProtocolReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomProtocolReq) ProtoMessage() {}

func (x *CustomProtocolReq) ProtoReflect() protoreflect.Message {
	mi := &file_dmsg_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomProtocolReq.ProtoReflect.Descriptor instead.
func (*CustomProtocolReq) Descriptor() ([]byte, []int) {
	return file_dmsg_proto_rawDescGZIP(), []int{17}
}

func (x *CustomProtocolReq) GetBasicData() *BasicData {
	if x != nil {
		return x.BasicData
	}
	return nil
}

func (x *CustomProtocolReq) GetPID() string {
	if x != nil {
		return x.PID
	}
	return ""
}

func (x *CustomProtocolReq) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

type CustomProtocolRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BasicData *BasicData `protobuf:"bytes,1,opt,name=basicData,proto3" json:"basicData,omitempty"`
	PID       string     `protobuf:"bytes,2,opt,name=pID,proto3" json:"pID,omitempty"`
	Content   []byte     `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	RetCode   *RetCode   `protobuf:"bytes,4,opt,name=retCode,proto3" json:"retCode,omitempty"`
}

func (x *CustomProtocolRes) Reset() {
	*x = CustomProtocolRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dmsg_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CustomProtocolRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomProtocolRes) ProtoMessage() {}

func (x *CustomProtocolRes) ProtoReflect() protoreflect.Message {
	mi := &file_dmsg_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomProtocolRes.ProtoReflect.Descriptor instead.
func (*CustomProtocolRes) Descriptor() ([]byte, []int) {
	return file_dmsg_proto_rawDescGZIP(), []int{18}
}

func (x *CustomProtocolRes) GetBasicData() *BasicData {
	if x != nil {
		return x.BasicData
	}
	return nil
}

func (x *CustomProtocolRes) GetPID() string {
	if x != nil {
		return x.PID
	}
	return ""
}

func (x *CustomProtocolRes) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *CustomProtocolRes) GetRetCode() *RetCode {
	if x != nil {
		return x.RetCode
	}
	return nil
}

var File_dmsg_proto protoreflect.FileDescriptor

var file_dmsg_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x64, 0x6d, 0x73, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62,
	0x22, 0x9a, 0x01, 0x0a, 0x09, 0x42, 0x61, 0x73, 0x69, 0x63, 0x44, 0x61, 0x74, 0x61, 0x12, 0x0e,
	0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44, 0x12, 0x19,
	0x0a, 0x03, 0x50, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x07, 0x2e, 0x70, 0x62,
	0x2e, 0x50, 0x49, 0x44, 0x52, 0x03, 0x50, 0x49, 0x44, 0x12, 0x0e, 0x0a, 0x02, 0x54, 0x53, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x54, 0x53, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x65, 0x65,
	0x72, 0x49, 0x44, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x65, 0x65, 0x72, 0x49,
	0x44, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x75, 0x62, 0x6b, 0x65, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x70, 0x75, 0x62, 0x6b, 0x65, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x69, 0x67,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x73, 0x69, 0x67, 0x12, 0x10, 0x0a, 0x03, 0x76,
	0x65, 0x72, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x76, 0x65, 0x72, 0x22, 0x35, 0x0a,
	0x07, 0x52, 0x65, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x22, 0x5b, 0x0a, 0x0e, 0x52, 0x65, 0x61, 0x64, 0x4d, 0x61, 0x69, 0x6c,
	0x62, 0x6f, 0x78, 0x52, 0x65, 0x71, 0x12, 0x2b, 0x0a, 0x09, 0x62, 0x61, 0x73, 0x69, 0x63, 0x44,
	0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x62, 0x2e, 0x42,
	0x61, 0x73, 0x69, 0x63, 0x44, 0x61, 0x74, 0x61, 0x52, 0x09, 0x62, 0x61, 0x73, 0x69, 0x63, 0x44,
	0x61, 0x74, 0x61, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x6c, 0x65, 0x61, 0x72, 0x4d, 0x6f, 0x64, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x63, 0x6c, 0x65, 0x61, 0x72, 0x4d, 0x6f, 0x64,
	0x65, 0x22, 0x39, 0x0a, 0x0b, 0x4d, 0x61, 0x69, 0x6c, 0x62, 0x6f, 0x78, 0x49, 0x74, 0x65, 0x6d,
	0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b,
	0x65, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x22, 0xb5, 0x01, 0x0a,
	0x0e, 0x52, 0x65, 0x61, 0x64, 0x4d, 0x61, 0x69, 0x6c, 0x62, 0x6f, 0x78, 0x52, 0x65, 0x73, 0x12,
	0x2b, 0x0a, 0x09, 0x62, 0x61, 0x73, 0x69, 0x63, 0x44, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x62, 0x2e, 0x42, 0x61, 0x73, 0x69, 0x63, 0x44, 0x61, 0x74,
	0x61, 0x52, 0x09, 0x62, 0x61, 0x73, 0x69, 0x63, 0x44, 0x61, 0x74, 0x61, 0x12, 0x31, 0x0a, 0x0b,
	0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x4d, 0x61, 0x69, 0x6c, 0x62, 0x6f, 0x78, 0x49, 0x74,
	0x65, 0x6d, 0x52, 0x0b, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x12,
	0x1c, 0x0a, 0x09, 0x65, 0x78, 0x69, 0x73, 0x74, 0x44, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x09, 0x65, 0x78, 0x69, 0x73, 0x74, 0x44, 0x61, 0x74, 0x61, 0x12, 0x25, 0x0a,
	0x07, 0x72, 0x65, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b,
	0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x07, 0x72, 0x65, 0x74,
	0x43, 0x6f, 0x64, 0x65, 0x22, 0x3f, 0x0a, 0x10, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4d, 0x61,
	0x69, 0x6c, 0x62, 0x6f, 0x78, 0x52, 0x65, 0x71, 0x12, 0x2b, 0x0a, 0x09, 0x62, 0x61, 0x73, 0x69,
	0x63, 0x44, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x62,
	0x2e, 0x42, 0x61, 0x73, 0x69, 0x63, 0x44, 0x61, 0x74, 0x61, 0x52, 0x09, 0x62, 0x61, 0x73, 0x69,
	0x63, 0x44, 0x61, 0x74, 0x61, 0x22, 0x66, 0x0a, 0x10, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4d,
	0x61, 0x69, 0x6c, 0x62, 0x6f, 0x78, 0x52, 0x65, 0x73, 0x12, 0x2b, 0x0a, 0x09, 0x62, 0x61, 0x73,
	0x69, 0x63, 0x44, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70,
	0x62, 0x2e, 0x42, 0x61, 0x73, 0x69, 0x63, 0x44, 0x61, 0x74, 0x61, 0x52, 0x09, 0x62, 0x61, 0x73,
	0x69, 0x63, 0x44, 0x61, 0x74, 0x61, 0x12, 0x25, 0x0a, 0x07, 0x72, 0x65, 0x74, 0x43, 0x6f, 0x64,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x74,
	0x43, 0x6f, 0x64, 0x65, 0x52, 0x07, 0x72, 0x65, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x22, 0x40, 0x0a,
	0x11, 0x52, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x4d, 0x61, 0x69, 0x6c, 0x62, 0x6f, 0x78, 0x52,
	0x65, 0x71, 0x12, 0x2b, 0x0a, 0x09, 0x62, 0x61, 0x73, 0x69, 0x63, 0x44, 0x61, 0x74, 0x61, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x62, 0x2e, 0x42, 0x61, 0x73, 0x69, 0x63,
	0x44, 0x61, 0x74, 0x61, 0x52, 0x09, 0x62, 0x61, 0x73, 0x69, 0x63, 0x44, 0x61, 0x74, 0x61, 0x22,
	0x67, 0x0a, 0x11, 0x52, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x4d, 0x61, 0x69, 0x6c, 0x62, 0x6f,
	0x78, 0x52, 0x65, 0x73, 0x12, 0x2b, 0x0a, 0x09, 0x62, 0x61, 0x73, 0x69, 0x63, 0x44, 0x61, 0x74,
	0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x62, 0x2e, 0x42, 0x61, 0x73,
	0x69, 0x63, 0x44, 0x61, 0x74, 0x61, 0x52, 0x09, 0x62, 0x61, 0x73, 0x69, 0x63, 0x44, 0x61, 0x74,
	0x61, 0x12, 0x25, 0x0a, 0x07, 0x72, 0x65, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x52,
	0x07, 0x72, 0x65, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x22, 0x3d, 0x0a, 0x0e, 0x53, 0x65, 0x65, 0x6b,
	0x4d, 0x61, 0x69, 0x6c, 0x62, 0x6f, 0x78, 0x52, 0x65, 0x71, 0x12, 0x2b, 0x0a, 0x09, 0x62, 0x61,
	0x73, 0x69, 0x63, 0x44, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e,
	0x70, 0x62, 0x2e, 0x42, 0x61, 0x73, 0x69, 0x63, 0x44, 0x61, 0x74, 0x61, 0x52, 0x09, 0x62, 0x61,
	0x73, 0x69, 0x63, 0x44, 0x61, 0x74, 0x61, 0x22, 0x64, 0x0a, 0x0e, 0x53, 0x65, 0x65, 0x6b, 0x4d,
	0x61, 0x69, 0x6c, 0x62, 0x6f, 0x78, 0x52, 0x65, 0x73, 0x12, 0x2b, 0x0a, 0x09, 0x62, 0x61, 0x73,
	0x69, 0x63, 0x44, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70,
	0x62, 0x2e, 0x42, 0x61, 0x73, 0x69, 0x63, 0x44, 0x61, 0x74, 0x61, 0x52, 0x09, 0x62, 0x61, 0x73,
	0x69, 0x63, 0x44, 0x61, 0x74, 0x61, 0x12, 0x25, 0x0a, 0x07, 0x72, 0x65, 0x74, 0x43, 0x6f, 0x64,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x74,
	0x43, 0x6f, 0x64, 0x65, 0x52, 0x07, 0x72, 0x65, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x22, 0x50, 0x0a,
	0x0f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x75, 0x62, 0x73, 0x75, 0x62, 0x52, 0x65, 0x71,
	0x12, 0x2b, 0x0a, 0x09, 0x62, 0x61, 0x73, 0x69, 0x63, 0x44, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x62, 0x2e, 0x42, 0x61, 0x73, 0x69, 0x63, 0x44, 0x61,
	0x74, 0x61, 0x52, 0x09, 0x62, 0x61, 0x73, 0x69, 0x63, 0x44, 0x61, 0x74, 0x61, 0x12, 0x10, 0x0a,
	0x03, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x22,
	0x65, 0x0a, 0x0f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x75, 0x62, 0x73, 0x75, 0x62, 0x52,
	0x65, 0x73, 0x12, 0x2b, 0x0a, 0x09, 0x62, 0x61, 0x73, 0x69, 0x63, 0x44, 0x61, 0x74, 0x61, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x62, 0x2e, 0x42, 0x61, 0x73, 0x69, 0x63,
	0x44, 0x61, 0x74, 0x61, 0x52, 0x09, 0x62, 0x61, 0x73, 0x69, 0x63, 0x44, 0x61, 0x74, 0x61, 0x12,
	0x25, 0x0a, 0x07, 0x72, 0x65, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0b, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x07, 0x72,
	0x65, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x22, 0x6f, 0x0a, 0x06, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x71,
	0x12, 0x2b, 0x0a, 0x09, 0x62, 0x61, 0x73, 0x69, 0x63, 0x44, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x62, 0x2e, 0x42, 0x61, 0x73, 0x69, 0x63, 0x44, 0x61,
	0x74, 0x61, 0x52, 0x09, 0x62, 0x61, 0x73, 0x69, 0x63, 0x44, 0x61, 0x74, 0x61, 0x12, 0x1e, 0x0a,
	0x0a, 0x64, 0x65, 0x73, 0x74, 0x50, 0x75, 0x62, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0a, 0x64, 0x65, 0x73, 0x74, 0x50, 0x75, 0x62, 0x6b, 0x65, 0x79, 0x12, 0x18, 0x0a,
	0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07,
	0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x22, 0x76, 0x0a, 0x06, 0x4d, 0x73, 0x67, 0x52, 0x65,
	0x73, 0x12, 0x2b, 0x0a, 0x09, 0x62, 0x61, 0x73, 0x69, 0x63, 0x44, 0x61, 0x74, 0x61, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x62, 0x2e, 0x42, 0x61, 0x73, 0x69, 0x63, 0x44,
	0x61, 0x74, 0x61, 0x52, 0x09, 0x62, 0x61, 0x73, 0x69, 0x63, 0x44, 0x61, 0x74, 0x61, 0x12, 0x25,
	0x0a, 0x07, 0x72, 0x65, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0b, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x07, 0x72, 0x65,
	0x74, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x22,
	0x4d, 0x0a, 0x0c, 0x51, 0x75, 0x65, 0x72, 0x79, 0x50, 0x65, 0x65, 0x72, 0x52, 0x65, 0x71, 0x12,
	0x2b, 0x0a, 0x09, 0x62, 0x61, 0x73, 0x69, 0x63, 0x44, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x62, 0x2e, 0x42, 0x61, 0x73, 0x69, 0x63, 0x44, 0x61, 0x74,
	0x61, 0x52, 0x09, 0x62, 0x61, 0x73, 0x69, 0x63, 0x44, 0x61, 0x74, 0x61, 0x12, 0x10, 0x0a, 0x03,
	0x70, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x70, 0x69, 0x64, 0x22, 0x62,
	0x0a, 0x0c, 0x51, 0x75, 0x65, 0x72, 0x79, 0x50, 0x65, 0x65, 0x72, 0x52, 0x65, 0x73, 0x12, 0x2b,
	0x0a, 0x09, 0x62, 0x61, 0x73, 0x69, 0x63, 0x44, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x62, 0x2e, 0x42, 0x61, 0x73, 0x69, 0x63, 0x44, 0x61, 0x74, 0x61,
	0x52, 0x09, 0x62, 0x61, 0x73, 0x69, 0x63, 0x44, 0x61, 0x74, 0x61, 0x12, 0x25, 0x0a, 0x07, 0x72,
	0x65, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x70,
	0x62, 0x2e, 0x52, 0x65, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x07, 0x72, 0x65, 0x74, 0x43, 0x6f,
	0x64, 0x65, 0x22, 0x6c, 0x0a, 0x11, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x50, 0x72, 0x6f, 0x74,
	0x6f, 0x63, 0x6f, 0x6c, 0x52, 0x65, 0x71, 0x12, 0x2b, 0x0a, 0x09, 0x62, 0x61, 0x73, 0x69, 0x63,
	0x44, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x62, 0x2e,
	0x42, 0x61, 0x73, 0x69, 0x63, 0x44, 0x61, 0x74, 0x61, 0x52, 0x09, 0x62, 0x61, 0x73, 0x69, 0x63,
	0x44, 0x61, 0x74, 0x61, 0x12, 0x10, 0x0a, 0x03, 0x70, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x70, 0x49, 0x44, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e,
	0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74,
	0x22, 0x93, 0x01, 0x0a, 0x11, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x50, 0x72, 0x6f, 0x74, 0x6f,
	0x63, 0x6f, 0x6c, 0x52, 0x65, 0x73, 0x12, 0x2b, 0x0a, 0x09, 0x62, 0x61, 0x73, 0x69, 0x63, 0x44,
	0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x62, 0x2e, 0x42,
	0x61, 0x73, 0x69, 0x63, 0x44, 0x61, 0x74, 0x61, 0x52, 0x09, 0x62, 0x61, 0x73, 0x69, 0x63, 0x44,
	0x61, 0x74, 0x61, 0x12, 0x10, 0x0a, 0x03, 0x70, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x70, 0x49, 0x44, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12,
	0x25, 0x0a, 0x07, 0x72, 0x65, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0b, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x07, 0x72,
	0x65, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x2a, 0x95, 0x03, 0x0a, 0x03, 0x50, 0x49, 0x44, 0x12, 0x16,
	0x0a, 0x12, 0x43, 0x52, 0x45, 0x41, 0x54, 0x45, 0x5f, 0x4d, 0x41, 0x49, 0x4c, 0x42, 0x4f, 0x58,
	0x5f, 0x52, 0x45, 0x51, 0x10, 0x00, 0x12, 0x16, 0x0a, 0x12, 0x43, 0x52, 0x45, 0x41, 0x54, 0x45,
	0x5f, 0x4d, 0x41, 0x49, 0x4c, 0x42, 0x4f, 0x58, 0x5f, 0x52, 0x45, 0x53, 0x10, 0x01, 0x12, 0x17,
	0x0a, 0x13, 0x52, 0x45, 0x4c, 0x45, 0x41, 0x53, 0x45, 0x5f, 0x4d, 0x41, 0x49, 0x4c, 0x42, 0x4f,
	0x58, 0x5f, 0x52, 0x45, 0x51, 0x10, 0x02, 0x12, 0x17, 0x0a, 0x13, 0x52, 0x45, 0x4c, 0x45, 0x41,
	0x53, 0x45, 0x5f, 0x4d, 0x41, 0x49, 0x4c, 0x42, 0x4f, 0x58, 0x5f, 0x52, 0x45, 0x53, 0x10, 0x03,
	0x12, 0x14, 0x0a, 0x10, 0x53, 0x45, 0x45, 0x4b, 0x5f, 0x4d, 0x41, 0x49, 0x4c, 0x42, 0x4f, 0x58,
	0x5f, 0x52, 0x45, 0x51, 0x10, 0x04, 0x12, 0x14, 0x0a, 0x10, 0x53, 0x45, 0x45, 0x4b, 0x5f, 0x4d,
	0x41, 0x49, 0x4c, 0x42, 0x4f, 0x58, 0x5f, 0x52, 0x45, 0x53, 0x10, 0x05, 0x12, 0x14, 0x0a, 0x10,
	0x52, 0x45, 0x41, 0x44, 0x5f, 0x4d, 0x41, 0x49, 0x4c, 0x42, 0x4f, 0x58, 0x5f, 0x52, 0x45, 0x51,
	0x10, 0x06, 0x12, 0x14, 0x0a, 0x10, 0x52, 0x45, 0x41, 0x44, 0x5f, 0x4d, 0x41, 0x49, 0x4c, 0x42,
	0x4f, 0x58, 0x5f, 0x52, 0x45, 0x53, 0x10, 0x07, 0x12, 0x19, 0x0a, 0x15, 0x43, 0x52, 0x45, 0x41,
	0x54, 0x45, 0x5f, 0x4d, 0x53, 0x47, 0x5f, 0x50, 0x55, 0x42, 0x53, 0x55, 0x42, 0x5f, 0x52, 0x45,
	0x51, 0x10, 0x08, 0x12, 0x19, 0x0a, 0x15, 0x43, 0x52, 0x45, 0x41, 0x54, 0x45, 0x5f, 0x4d, 0x53,
	0x47, 0x5f, 0x50, 0x55, 0x42, 0x53, 0x55, 0x42, 0x5f, 0x52, 0x45, 0x53, 0x10, 0x09, 0x12, 0x0b,
	0x0a, 0x07, 0x4d, 0x53, 0x47, 0x5f, 0x52, 0x45, 0x51, 0x10, 0x0a, 0x12, 0x0b, 0x0a, 0x07, 0x4d,
	0x53, 0x47, 0x5f, 0x52, 0x45, 0x53, 0x10, 0x0b, 0x12, 0x16, 0x0a, 0x12, 0x43, 0x52, 0x45, 0x41,
	0x54, 0x45, 0x5f, 0x43, 0x48, 0x41, 0x4e, 0x4e, 0x45, 0x4c, 0x5f, 0x52, 0x45, 0x51, 0x10, 0x0c,
	0x12, 0x16, 0x0a, 0x12, 0x43, 0x52, 0x45, 0x41, 0x54, 0x45, 0x5f, 0x43, 0x48, 0x41, 0x4e, 0x4e,
	0x45, 0x4c, 0x5f, 0x52, 0x45, 0x53, 0x10, 0x0d, 0x12, 0x12, 0x0a, 0x0e, 0x51, 0x55, 0x45, 0x52,
	0x59, 0x5f, 0x50, 0x45, 0x45, 0x52, 0x5f, 0x52, 0x45, 0x51, 0x10, 0x0e, 0x12, 0x12, 0x0a, 0x0e,
	0x51, 0x55, 0x45, 0x52, 0x59, 0x5f, 0x50, 0x45, 0x45, 0x52, 0x5f, 0x52, 0x45, 0x53, 0x10, 0x0f,
	0x12, 0x15, 0x0a, 0x11, 0x43, 0x55, 0x53, 0x54, 0x4f, 0x4d, 0x5f, 0x53, 0x54, 0x52, 0x45, 0x41,
	0x4d, 0x5f, 0x52, 0x45, 0x51, 0x10, 0x10, 0x12, 0x15, 0x0a, 0x11, 0x43, 0x55, 0x53, 0x54, 0x4f,
	0x4d, 0x5f, 0x53, 0x54, 0x52, 0x45, 0x41, 0x4d, 0x5f, 0x52, 0x45, 0x53, 0x10, 0x11, 0x42, 0x09,
	0x5a, 0x07, 0x64, 0x6d, 0x73, 0x67, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_dmsg_proto_rawDescOnce sync.Once
	file_dmsg_proto_rawDescData = file_dmsg_proto_rawDesc
)

func file_dmsg_proto_rawDescGZIP() []byte {
	file_dmsg_proto_rawDescOnce.Do(func() {
		file_dmsg_proto_rawDescData = protoimpl.X.CompressGZIP(file_dmsg_proto_rawDescData)
	})
	return file_dmsg_proto_rawDescData
}

var file_dmsg_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_dmsg_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_dmsg_proto_goTypes = []interface{}{
	(PID)(0),                  // 0: pb.PID
	(*BasicData)(nil),         // 1: pb.BasicData
	(*RetCode)(nil),           // 2: pb.RetCode
	(*ReadMailboxReq)(nil),    // 3: pb.ReadMailboxReq
	(*MailboxItem)(nil),       // 4: pb.MailboxItem
	(*ReadMailboxRes)(nil),    // 5: pb.ReadMailboxRes
	(*CreateMailboxReq)(nil),  // 6: pb.CreateMailboxReq
	(*CreateMailboxRes)(nil),  // 7: pb.CreateMailboxRes
	(*ReleaseMailboxReq)(nil), // 8: pb.ReleaseMailboxReq
	(*ReleaseMailboxRes)(nil), // 9: pb.ReleaseMailboxRes
	(*SeekMailboxReq)(nil),    // 10: pb.SeekMailboxReq
	(*SeekMailboxRes)(nil),    // 11: pb.SeekMailboxRes
	(*CreatePubsubReq)(nil),   // 12: pb.CreatePubsubReq
	(*CreatePubsubRes)(nil),   // 13: pb.CreatePubsubRes
	(*MsgReq)(nil),            // 14: pb.MsgReq
	(*MsgRes)(nil),            // 15: pb.MsgRes
	(*QueryPeerReq)(nil),      // 16: pb.QueryPeerReq
	(*QueryPeerRes)(nil),      // 17: pb.QueryPeerRes
	(*CustomProtocolReq)(nil), // 18: pb.CustomProtocolReq
	(*CustomProtocolRes)(nil), // 19: pb.CustomProtocolRes
}
var file_dmsg_proto_depIdxs = []int32{
	0,  // 0: pb.BasicData.PID:type_name -> pb.PID
	1,  // 1: pb.ReadMailboxReq.basicData:type_name -> pb.BasicData
	1,  // 2: pb.ReadMailboxRes.basicData:type_name -> pb.BasicData
	4,  // 3: pb.ReadMailboxRes.contentList:type_name -> pb.MailboxItem
	2,  // 4: pb.ReadMailboxRes.retCode:type_name -> pb.RetCode
	1,  // 5: pb.CreateMailboxReq.basicData:type_name -> pb.BasicData
	1,  // 6: pb.CreateMailboxRes.basicData:type_name -> pb.BasicData
	2,  // 7: pb.CreateMailboxRes.retCode:type_name -> pb.RetCode
	1,  // 8: pb.ReleaseMailboxReq.basicData:type_name -> pb.BasicData
	1,  // 9: pb.ReleaseMailboxRes.basicData:type_name -> pb.BasicData
	2,  // 10: pb.ReleaseMailboxRes.retCode:type_name -> pb.RetCode
	1,  // 11: pb.SeekMailboxReq.basicData:type_name -> pb.BasicData
	1,  // 12: pb.SeekMailboxRes.basicData:type_name -> pb.BasicData
	2,  // 13: pb.SeekMailboxRes.retCode:type_name -> pb.RetCode
	1,  // 14: pb.CreatePubsubReq.basicData:type_name -> pb.BasicData
	1,  // 15: pb.CreatePubsubRes.basicData:type_name -> pb.BasicData
	2,  // 16: pb.CreatePubsubRes.retCode:type_name -> pb.RetCode
	1,  // 17: pb.MsgReq.basicData:type_name -> pb.BasicData
	1,  // 18: pb.MsgRes.basicData:type_name -> pb.BasicData
	2,  // 19: pb.MsgRes.retCode:type_name -> pb.RetCode
	1,  // 20: pb.QueryPeerReq.basicData:type_name -> pb.BasicData
	1,  // 21: pb.QueryPeerRes.basicData:type_name -> pb.BasicData
	2,  // 22: pb.QueryPeerRes.retCode:type_name -> pb.RetCode
	1,  // 23: pb.CustomProtocolReq.basicData:type_name -> pb.BasicData
	1,  // 24: pb.CustomProtocolRes.basicData:type_name -> pb.BasicData
	2,  // 25: pb.CustomProtocolRes.retCode:type_name -> pb.RetCode
	26, // [26:26] is the sub-list for method output_type
	26, // [26:26] is the sub-list for method input_type
	26, // [26:26] is the sub-list for extension type_name
	26, // [26:26] is the sub-list for extension extendee
	0,  // [0:26] is the sub-list for field type_name
}

func init() { file_dmsg_proto_init() }
func file_dmsg_proto_init() {
	if File_dmsg_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_dmsg_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BasicData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dmsg_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RetCode); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dmsg_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadMailboxReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dmsg_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MailboxItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dmsg_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadMailboxRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dmsg_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateMailboxReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dmsg_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateMailboxRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dmsg_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReleaseMailboxReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dmsg_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReleaseMailboxRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dmsg_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SeekMailboxReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dmsg_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SeekMailboxRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dmsg_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreatePubsubReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dmsg_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreatePubsubRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dmsg_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dmsg_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dmsg_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryPeerReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dmsg_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryPeerRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dmsg_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CustomProtocolReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dmsg_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CustomProtocolRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_dmsg_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_dmsg_proto_goTypes,
		DependencyIndexes: file_dmsg_proto_depIdxs,
		EnumInfos:         file_dmsg_proto_enumTypes,
		MessageInfos:      file_dmsg_proto_msgTypes,
	}.Build()
	File_dmsg_proto = out.File
	file_dmsg_proto_rawDesc = nil
	file_dmsg_proto_goTypes = nil
	file_dmsg_proto_depIdxs = nil
}
